services:
    php:
        container_name: olx-price-service
        restart: unless-stopped
        build:
            args:
                user: '${WWWUSER}'
                uid: '${WWWUID}'
                group: '${WWWGROUP}'
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - backend
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - backend
        restart: unless-stopped
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    nginx:
        container_name: nginx-olx-price-service
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - backend
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - backend
networks:
    backend:
        driver: bridge
